### ISSUE TITLE
[Questionnaire] pagination

### ISSUE THREAD

**Issue by hagitta** [Prize4Life/Android#121]
once you go into the questionnaire, you can slide the screen left and right to paginate; however, the step numbers at the bottom don't update.

**Comment by arisprung** [comment]
Fixed

**Comment by MichaelG12345** [comment]
Not completely fixed. When you use the slide action to paginate and get to the last step (#12), the Submit button doesn't appear.

**Comment by arisprung** [comment]
Fixed completely.

Good catch!
